#!/usr/bin/env bash
# This installs the web server 'nginx' on the server and perform some configurations
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html

rewrite="server {
        listen 80;
        listen [::]:80;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
	location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

echo -e "$rewrite" > /etc/nginx/sites-available/redirect
ln -sf /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
sudo nginx -t
service nginx restart
