#!/usr/bin/env bash
# This installs the web server 'nginx' on the server and perform some configurations
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html

new_website=\
"server {
        listen 80;
        listen [::]:80;
        
        server_name devmohzis.tech;
        
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html 404.html;
        
        location / {
                try_files $uri $uri/ =404;
        }
            location /redirect_me {
            return 301 https://www.youtube.com/@mosesisang9974;
}"

echo -e "$rewrite" > /etc/nginx/sites-available/redirect
ln -sf /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
sudo nginx -t
service nginx restart
