#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Requirements:

# Configures HAproxy so that it send traffic to web-01 and web-02
# Distributes requests using a roundrobin algorithm
# Makes sure that HAproxy can be managed via an init script
# Makes sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.


sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo  apt-get -y  install haproxy=2.6.\*

# parameters

domain_name='codewithalareef.tech'
init_file='/etc/default/haproxy'
config_file='/etc/haproxy/haproxy.cfg'

