#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Requirements:

# Configures HAproxy so that it send traffic to web-01 and web-02
# Distributes requests using a roundrobin algorithm
# Makes sure that HAproxy can be managed via an init script
# Makes sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.


sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo  apt-get -y  install haproxy=2.6.\*

# parameters
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 176695-web-02 54.160.82.24 check\n\tserver 176695-web-01 34.239.207.58 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
