#!/usr/bin/env bash

#Creates a serverr
SERVER="8.8.8.8"

#Creates the username to use for the ssh connection
USERNAME="ubuntu"

#Set the path to private key
PRIVATE_KEY="~/.ssh/school"

ssh -i ~/.ssh/school ubuntu@8.8.8.8
