#!/usr/bin/env bash
# Creates a server
SERVER="98.98.98.98"

# Creates the username to use for the ssh connection
USERNAME="ubuntu"

# Set the path to private key
PRIVATE_KEY="~/.ssh/school"

ssh -i ~/.ssh/school ubuntu@98.98.98.98
