#!/usr/bin/env bash
# Creates a server
SERVER="54.87.210.150"

# Creates the username to use for the ssh connection
USERNAME="ubuntu"

# Set the path to private key
PRIVATE_KEY="~/.ssh/school"

ssh -i ~/.ssh/school ubuntu@54.87.210.150
